<?php
function thumboverlays_form_project_node_form_alter(&$form, &$form_state, $form_id) {
   $path = drupal_get_path('module', 'thumboverlays');
   $settings['thumboverlays'] = array('path' => $path);
   drupal_add_js($settings, 'setting');
   $form['#attached']['js'] = array(
      $path .'/js/thumboverlays.js',
   );
   $form['#attached']['css'] = array(
      $path .'/css/thumboverlays.css',
   );
}

function thumboverlays_form_milestone_node_form_alter(&$form, &$form_state, $form_id) {
   $form['#attached']['js'] = array(
      drupal_get_path('module', 'thumboverlays') .'/js/thumboverlays.js',
   );
   $form['#attached']['css'] = array(
      drupal_get_path('module', 'thumboverlays') .'/css/thumboverlays.css',
   );
}
/*function thumboverlays_form_alter(&$form, &$form_state, $form_id) {
   dsm($form_id);
} */


function thumboverlays_preprocess_node(&$variables) {
   switch($variables['type']) {
      case "project":
      case "milestone":
         $path = drupal_get_path('module', 'thumboverlays');
         $settings['thumboverlays'] = array('path' => $path.'/images/');
         drupal_add_js($settings, 'setting');
         drupal_add_css(drupal_get_path('module', 'thumboverlays') . '/css/thumboverlays.css');
         break;
      default:
         break;
   }
}