<?php

function thumboverlays_form_alter(&$form, &$form_state, $form_id) {
   switch ($form_id) {
      case "milestone_node_form":
      case "project_node_form":
         $isEdit = true;
         setBehaviorsSettings($isEdit);
         $form['#attached']['js'][] = drupal_get_path('module', 'thumboverlays') .'/js/thumboverlays.js';
         break;
      default:
         //no nothing
            break;
   }
} 

function thumboverlays_preprocess_node(&$variables) {
   //dsm($variables['type']);
   switch($variables['type']) {
      case "project":
      case "milestone":
         $isEdit = false;
         setBehaviorsSettings($isEdit);
         drupal_add_css(drupal_get_path('module', 'thumboverlays') . '/css/thumboverlays.css');
         drupal_add_js(drupal_get_path('module', 'thumboverlays') . '/js/thumboverlays.js');
         break;
      default:
         break;
   }
}

function setBehaviorsSettings($onEditForm) {
   $path = drupal_get_path('module', 'thumboverlays');
   $settings['thumboverlays']['path'] = $path.'/images/';
   $settings['thumboverlays']['editform']= $onEditForm;
   $selectors = Array();
   if ($onEditForm) {
      $settings['thumboverlays']['prepend'] = '#edit-';
      $settings['thumboverlays']['videoSelector'] = '.file-widget .file';
      $settings['thumboverlays']['imageSelector'] = '.image-widget .image-widget-data .file';
   }
   else {
      $settings['thumboverlays']['prepend'] = '.field-name-';
      $settings['thumboverlays']['videoSelector'] = '.field-item .file';
      $settings['thumboverlays']['imageSelector'] = '.field-item img';
   }
   drupal_add_js($settings, 'setting');
}